"""add country table

Revision ID: 7fa2a57b5bc2
Revises: af89c0fc82cd
Create Date: 2026-08-19 19:14:58.615778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa2a57b5bc2'
down_revision: Union[str, Sequence[str], None] = 'af89c0fc82cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
