"""init

Revision ID: af89c0fc82cd
Revises: 
Create Date: 2026-07-27 19:40:32.439588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'af89c0fc82cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('scraped_flights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_name', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('dep_iata', sa.String(length=3), nullable=False),
    sa.Column('arr_iata', sa.String(length=3), nullable=False),
    sa.Column('dep_time_utc', sa.Integer(), nullable=False),
    sa.Column('arr_time_utc', sa.Integer(), nullable=False),
    sa.Column('flight_time_mins', sa.Integer(), nullable=False),
    sa.Column('scraped_at_utc', sa.Integer(), nullable=False),
    sa.Column('seats_left', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_currency', sa.String(), nullable=False),
    sa.Column('price_in_euro', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['arr_iata'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['dep_iata'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_flights')
    op.drop_table('airports')
    # ### end Alembic commands ###
